#!/bin/bash
#############################################################################
# TYRONE AI - Template System Installation
# 
# This creates your PERMANENT template that NEVER gets modified.
# Use `tyrone <project-name>` to spin up new projects from it.
#############################################################################

set -e

TEMPLATE_DIR="$HOME/.tyrone-ai-template"
PROJECTS_DIR="$HOME/projects"
BIN_DIR="$HOME/.local/bin"

echo "╔════════════════════════════════════════════════════════════════════╗"
echo "║              TYRONE AI - Template System Setup                    ║"
echo "╚════════════════════════════════════════════════════════════════════╝"

# Create directories
echo "[1/6] Creating directories..."
mkdir -p "$TEMPLATE_DIR"
mkdir -p "$PROJECTS_DIR"
mkdir -p "$BIN_DIR"

# Create the master template (THIS NEVER CHANGES)
echo "[2/6] Creating master template..."

cat > "$TEMPLATE_DIR/MASTER-TEMPLATE.md" << 'TEMPLATE'
# TYRONE AI - Project Template
# =============================
# DO NOT EDIT THIS FILE - It's your master template
# Use `tyrone <project-name>` to create new projects
#
# This template automatically includes:
# - Full autonomous execution protocol
# - All your skills (autonomous-execution-protocol, no-human-in-the-loop)
# - Pre-approved permissions
# - Session state persistence
# - API keys from environment
#
# When you run `tyrone my-project`:
# 1. Creates ~/projects/my-project/
# 2. Copies template structure
# 3. Initializes git
# 4. Sets up session state
# 5. Ready for `claude` command
#
# Your current builds (like Orleans) stay separate.
# Template stays CLEAN forever.
TEMPLATE

# Create the launcher script
echo "[3/6] Installing tyrone command..."

cat > "$BIN_DIR/tyrone" << 'LAUNCHER'
#!/bin/bash
#############################################################################
# TYRONE AI - Project Launcher
# Usage: tyrone <project-name>
#############################################################################

set -e

PROJECTS_DIR="$HOME/projects"
TIMESTAMP=$(date -u +"%Y-%m-%dT%H:%M:%SZ")

if [ -z "$1" ]; then
    echo "TYRONE AI - Project Launcher"
    echo ""
    echo "Usage: tyrone <project-name>"
    echo ""
    echo "Examples:"
    echo "  tyrone my-new-app"
    echo "  tyrone client-dashboard"
    echo "  tyrone ml-experiment"
    echo ""
    echo "This creates a new project at ~/projects/<name> with:"
    echo "  - Full autonomous Claude config"
    echo "  - Session state persistence"
    echo "  - Git initialized"
    echo "  - Ready for 'claude' command"
    echo ""
    echo "Your existing projects:"
    ls -1 "$PROJECTS_DIR" 2>/dev/null || echo "  (none yet)"
    exit 0
fi

PROJECT_NAME="$1"
PROJECT_DIR="$PROJECTS_DIR/$PROJECT_NAME"

echo "🚀 TYRONE AI - Launching: $PROJECT_NAME"

if [ -d "$PROJECT_DIR" ]; then
    echo "Project exists. Opening..."
    cd "$PROJECT_DIR"
    pwd
    exit 0
fi

echo "Creating new project..."
mkdir -p "$PROJECT_DIR/.claude/commands"

# Project CLAUDE.md
cat > "$PROJECT_DIR/CLAUDE.md" << CLAUDEMD
# Project: $PROJECT_NAME
# Created: $TIMESTAMP
# Template: TYRONE AI

## AUTONOMOUS MODE ACTIVE
Inherits from ~/.claude/CLAUDE.md. FULL POWER OF AUTHORITY granted.

## Project Brief
<!-- Fill this once, then Claude executes -->

### Building:


### Stack:


### Constraints:


### Success =


## Session Log
- $TIMESTAMP: Initialized from TYRONE AI
CLAUDEMD

# Session state
cat > "$PROJECT_DIR/.claude-session-state.json" << STATE
{
  "version": "1.0.0",
  "session_id": "${RANDOM}${RANDOM}",
  "created_at": "$TIMESTAMP",
  "last_updated": "$TIMESTAMP",
  "project": {
    "name": "$PROJECT_NAME",
    "root_path": "$PROJECT_DIR",
    "template": "TYRONE AI"
  },
  "execution_state": {
    "current_task": "Awaiting project brief",
    "completed_tasks": ["Template setup"],
    "pending_tasks": []
  },
  "decisions_made": [],
  "files_modified": [],
  "notes": ["Fresh from TYRONE AI template"]
}
STATE

# Project settings
cat > "$PROJECT_DIR/.claude/settings.json" << 'SETTINGS'
{"permissions":{"allow":["Read","Write","Edit","Bash(*)","Glob","Grep","Search","mcp__*"],"deny":[]}}
SETTINGS

# Gitignore
cat > "$PROJECT_DIR/.gitignore" << 'GIT'
.claude-session-state.json
.claude/settings.local.json
.env
.env.*
node_modules/
venv/
__pycache__/
dist/
build/
.DS_Store
GIT

# Git init
cd "$PROJECT_DIR"
git init -q
git add -A
git commit -q -m "Init from TYRONE AI"

echo ""
echo "✅ Project ready: $PROJECT_DIR"
echo ""
echo "Next:"
echo "  cd $PROJECT_DIR"
echo "  claude"
echo ""
LAUNCHER

chmod +x "$BIN_DIR/tyrone"

# Add to PATH if not already
echo "[4/6] Configuring PATH..."
for profile in "$HOME/.bashrc" "$HOME/.zshrc" "$HOME/.profile"; do
    if [ -f "$profile" ]; then
        if ! grep -q '.local/bin' "$profile" 2>/dev/null; then
            echo 'export PATH="$HOME/.local/bin:$PATH"' >> "$profile"
        fi
    fi
done

# Create quick-access alias
echo "[5/6] Creating aliases..."
for profile in "$HOME/.bashrc" "$HOME/.zshrc"; do
    if [ -f "$profile" ]; then
        if ! grep -q 'alias projects=' "$profile" 2>/dev/null; then
            echo 'alias projects="ls -la ~/projects"' >> "$profile"
            echo 'alias cdp="cd ~/projects"' >> "$profile"
        fi
    fi
done

echo "[6/6] Complete!"

echo ""
echo "╔════════════════════════════════════════════════════════════════════╗"
echo "║              TYRONE AI INSTALLED 🚀                               ║"
echo "╚════════════════════════════════════════════════════════════════════╝"
echo ""
echo "Commands:"
echo "  tyrone <name>  - Create/open a project"
echo "  projects       - List all projects"
echo "  cdp            - Jump to projects folder"
echo ""
echo "Your template is PROTECTED at: ~/.tyrone-ai-template/"
echo "New projects go to: ~/projects/<name>/"
echo ""
echo "Restart terminal or run: export PATH=\"\$HOME/.local/bin:\$PATH\""
echo ""
echo "Example:"
echo "  tyrone my-killer-app"
echo "  cd ~/projects/my-killer-app"
echo "  claude"
echo ""
